version: '3'

services:
  api-gateway:
    build:
      context: ./gateway
    container_name: api-gateway
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  people-service:
    build: ./people_service
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./people_service:/app

  movie-service:
    build: ./movie_service
    ports:
      - "8001:8001"
    depends_on:
      - people-service
    networks:
      - app-network
    volumes:
      - ./movie_service:/app
  
networks:
  app-network:
    driver: bridge
